# Generated by Django 4.0.4 on 2022-04-23 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('img', models.ImageField(upload_to='post/')),
                ('image', models.ImageField(upload_to='post/')),
                ('genre', models.CharField(max_length=225)),
                ('Written_by', models.CharField(max_length=225)),
                ('Created_by', models.CharField(max_length=225)),
                ('Release_dates', models.CharField(max_length=225)),
                ('Language', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=225, unique_for_date='published_at')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='1', max_length=1)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
