# Generated by Django 4.0.4 on 2022-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_card_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='best_film',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='card',
            name='best_series',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='card',
            name='imdb',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
